@@ -0,0 +1,20 @@
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:midas
    username: sweta
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: midas-group
      auto-offset-reset: earliest

general:
  kafka-topic: midas-transactions
